'use client';
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {config} from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ProgressBar from "@/components/progressBar";
import {usePathname} from "next/navigation";

const inter = Inter({subsets: ["latin"]});
config.autoAddCss = false;
const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    const pathName: string = usePathname()
    const isHomePage: boolean = pathName === '/'
    return (
        <html lang="en">
        <body className={inter.className}>
        <ProgressBar/>
        <main className={`mt-20 min-h-screen ${isHomePage ? "bg-homeBg" : ""} bg-cover`}>
            <Header/>
            <div className="min-h-[90vh]">
                {children}
            </div>
            <Footer/>
        </main>
        </body>
        </html>
    );
}
